---
permalink: protect/task_configure_sra_on_srm_appliance.html 
sidebar: sidebar 
keywords:  
summary: 'Después de implementar el dispositivo de SRM, debe configurar SRA en el dispositivo de SRM. La configuración correcta del SRA permite que el dispositivo SRM se comunique con el SRA para la gestión de la recuperación ante desastres. Debe almacenar las credenciales de las herramientas de ONTAP \(dirección IP y contraseña de administrador\) en el dispositivo de SRM para habilitar la comunicación entre el dispositivo SRM y el SRA.' 
---
= Configure SRA en el dispositivo SRM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de implementar el dispositivo de SRM, debe configurar SRA en el dispositivo de SRM. La configuración correcta del SRA permite que el dispositivo SRM se comunique con el SRA para la gestión de la recuperación ante desastres. Debe almacenar las credenciales de herramientas de ONTAP (dirección IP y contraseña de administrador) en el dispositivo de SRM para habilitar la comunicación entre SRM Appliance y SRA.

*Lo que necesitará*

Debe haber cargado el archivo _tar.gz_ en SRM Appliance.

*Acerca de esta tarea*

La configuración del SRA en el dispositivo de SRM almacena las credenciales del SRA en el dispositivo de SRM.

* Pasos*

. Inicie sesión utilizando la cuenta de administrador en el dispositivo SRM utilizando putty.
. Cambie al usuario raíz mediante el comando: `su root`
. En la ubicación de registro, introduzca el comando para obtener el ID de Docker que utiliza el Docker de SRA `ps -l`
. Para iniciar sesión en el ID del contenedor, introduzca command docker `exec -it -u srm <container id> sh`
. Configure SRM con la dirección IP y la contraseña de ONTAP Tools mediante el comando: `perl command.pl -I <va-IP> administrator <va-password>``
+
Se muestra un mensaje indicando que las credenciales de almacenamiento están almacenadas correctamente. El SRA puede comunicarse con el servidor SRA mediante la dirección IP, el puerto y las credenciales proporcionados.


